Repository HermesCS/Hermes, pull requests merged in 2023-09, with the labels that each got.

#12 refactor: 🔁 resolve HermesCS/Hermes#10
  api/src/hubs/auth.guard.js
  api/src/hubs/message.tunnel.js
  api/src/services/token.service.js
  api/src/socket.js
Labels: refactor

#13 feature: ⚙️ get profile infomation from access token GET /profile
  api/readme.md
  api/src/app.js
  api/src/authorization/auth.middlewere.js
  api/src/core/models/user.js
  api/src/features/profiles/from-token.js
  api/src/features/profiles/profile.route.js
Labels: feature

#15 features: ⚙️add get chat history `GET` /chat/histories
  api/readme.md
  api/src/app.js
  api/src/features/chats/chat-history.js
  api/src/features/chats/chat.route.js
  api/src/hubs/message.tunnel.js
Labels: refactor, feature

#16 fix : 🔧 error when send message to chat room which have no permission
  api/src/hubs/message.tunnel.js
Labels: bug

#19 fix: 🔧 add error handler when send empty message or chat id
  api/src/hubs/message.tunnel.js
Labels: bug

#21 implement add chat ui
  app/src/layout/Sidebar/AddConnector/AddConnector.tsx
  app/src/layout/Sidebar/AddConnector/ConnectorCard.tsx
  app/src/layout/Sidebar/AddConnector/GroupPanel.tsx
  app/src/layout/Sidebar/AddConnector/PrivatePanel.tsx
  app/src/layout/Sidebar/AddConnectorButton.tsx
  app/src/layout/Sidebar/Sidebar.tsx
  app/src/models/chat.ts
Labels: feature

#22 change mock and group layput
  app/package-lock.json
  app/package.json
  app/src/App.tsx
  app/src/components/Chat/ChatBox.tsx
  app/src/components/Connector/ConnectorList.tsx
  app/src/components/Message.tsx
  app/src/layout/ChatInterface/ChatBox/ChatBox.tsx
  app/src/layout/ChatInterface/ChatHeader/ChatHeader.tsx
  app/src/layout/ChatInterface/ChatInterface.tsx
  app/src/layout/ChatInterface/TextBox.tsx/TextBox.tsx
  app/src/layout/Sidebar/Brand/Brand.tsx
  app/src/layout/Sidebar/ChatContact/ChatContact.css
  app/src/layout/Sidebar/ChatContact/ChatContact.tsx
  app/src/layout/Sidebar/ChatContact/ChatContactList.tsx
  app/src/layout/Sidebar/ChatContactFilter/ConnectorFilter.tsx
  app/src/layout/Sidebar/ConnectorFilter.tsx
  app/src/layout/Sidebar/MainSettings/MainSettings.tsx
  app/src/layout/Sidebar/OwnerPanel/OwnerPanel.tsx
  app/src/layout/Sidebar/Searchbar/Searchbar.tsx
  app/src/layout/Sidebar/Sidebar.tsx
  app/src/mockData.ts
  app/src/utilities.ts
Labels: enhancement

#23 Main feat v2
  api/.ENV.DEV
  api/package-lock.json
  api/package.json
  api/src/app.js
  api/src/authorization/auth-login.js
  api/src/authorization/auth-refresh.js
  api/src/authorization/auth-register.js
  api/src/authorization/auth.middlewere.js
  api/src/authorization/auth.rout.js
  api/src/config/mongodb.config.js
  api/src/core/mock.js
  api/src/core/models/chat.js
  api/src/core/models/message.js
  api/src/core/models/user.js
  api/src/features/chat-contact/chat-contact.js
  api/src/features/chat-contact/chat-contact.rout.js
  api/src/features/users/users-profile.js
  api/src/features/users/users-profile.rout.js
  api/src/hubs/auth.guard.js
  api/src/hubs/message.tunnel.js
  api/src/services/token.service.js
  app/src/layout/ChatInterface.tsx
  app/yarn.lock
  package-lock.json
Labels: feature

#27 refactor: 🔁 set enviroment file to one file `/bin/www`
  api/bin/www
  api/src/authorization/auth-login.js
  api/src/authorization/auth-refresh.js
  api/src/authorization/auth-register.js
  api/src/authorization/auth.middlewere.js
  api/src/authorization/auth.rout.js
  api/src/config/mongodb.config.js
Labels: refactor

#29 add push message
  app/src/components/Message.tsx
  app/src/layout/ChatInterface/ChatBox/ChatBox.tsx
  app/src/layout/ChatInterface/ChatInterface.tsx
  app/src/layout/ChatInterface/TextBox.tsx/TextBox.tsx
  app/src/models/message-context.ts
  app/src/services/chat-service.ts
  package-lock.json
Labels: feature

#30 refactor:🔁 re-route
  api/readme.md
  api/src/app.js
  api/src/authorization/auth.rout.js
  api/src/features/chat-contact/chat-contact.rout.js
  api/src/features/chats/chat-history.js
  api/src/features/chats/chat.route.js
  api/src/features/chats/get-chats.js
  api/src/features/profiles/from-id.js
  api/src/features/profiles/profile.route.js
  api/src/features/users/users-profile.rout.js
  api/src/hubs/message.tunnel.js
Labels: refactor

#33 feature: add `POST` /chat
  api/src/core/models/chat.js
  api/src/features/chats/add-chat.js
  api/src/features/chats/chat.route.js
  app/src/models/chat.ts
Labels: feature

#34 Feature: ⚙️ update profile
  api/readme.md
  api/src/app.js
  api/src/features/profiles/patch-avatar.js
  api/src/features/profiles/patch-display-name.js
  api/src/features/profiles/profile.route.js
Labels: feature

#35 Chat filter
  api/package-lock.json
  api/package.json
  api/src/app.js
  api/src/features/profiles/patch-avatar.js
  api/src/hubs/auth.guard.js
  app/package.json
  app/src/context/AuthContext.tsx
  app/src/layout/Sidebar/AddConnector/ConnectorCard.tsx
  app/src/layout/Sidebar/AddConnector/PrivatePanel.tsx
  app/src/layout/Sidebar/ChatContactFilter/ConnectorFilter.tsx
  app/src/layout/Sidebar/Sidebar.tsx
  app/src/models/response.ts
  app/src/pages/LoginPage.tsx
  app/src/pages/Plain.tsx
  app/src/services/auth-service.ts
  app/src/services/connector-service.ts
  app/src/services/http-service.ts
  app/src/services/local-storage-service.ts
  app/src/value-object.ts
Labels: bug, feature
